# Generated by Django 5.0.4 on 2024-05-05 08:25

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_angkatan_profiladmin_profilguru_profilsiswa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angkatan',
            name='tahun_ajaran',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1984), app.models.max_value_current_year]),
        ),
    ]
