# Generated by Django 5.0.4 on 2024-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_angkatan_tahun_ajaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiladmin',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profilguru',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profilsiswa',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
