# Generated by Django 5.0.4 on 2024-05-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jadwal_profilsiswa_hash_profilsiswa_nisn_absensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiladmin',
            name='alamat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profiladmin',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profiladmin',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilguru',
            name='alamat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilguru',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilguru',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilsiswa',
            name='alamat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilsiswa',
            name='angkatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.angkatan'),
        ),
        migrations.AlterField(
            model_name='profilsiswa',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilsiswa',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
