# Generated by Django 5.0.4 on 2024-05-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profiladmin_alamat_alter_profiladmin_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absensi',
            unique_together={('profil_siswa', 'jadwal', 'tanggal')},
        ),
    ]
